### ISSUE TITLE
how to adjust move forward distance objectnav_hm3d.yaml

### ISSUE THREAD

**Issue by githubLeoliu** [facebookresearch/habitat-sim#2558]
```
# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/objectnav: hm3d
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
        height: 0.88
        radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
```

The variable "turn_angle: 30" adjust the magnitude of action 3 and 4 (turn left or right). Is there a variable to adjust magnitude of moving forward?
