### ISSUE TITLE
Episode ends at step before MAX_EPISODE_STEPS

### ISSUE THREAD

**Issue by chenwydj** [facebookresearch/habitat-sim#265]
## ❓ Questions and Help

When I use the following yaml file, the episode sometimes ends at a step before the MAX_EPISODE_STEPS
```yaml
ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'SEMANTIC_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
```

I don't understand why the episode ends. Ideally, in the yaml file above I did not assign any navigation task, and the agent should freely wandering in the room. How do I correctly config the dataset without any specific task in yaml file, in order to keep the agent walking?

Thank you very much!
